### ISSUE TITLE
How to call elasticsearch:import:model from another Rake task?

### ISSUE THREAD

**Issue by netwire88** [elasticsearch/elasticsearch-rails#266]
Hi,
I have a fairly simple question. How can I call something like `bundle exec rake environment elasticsearch:import:model CLASS='User' SCOPE='active' FORCE=y` from within another Rake task? 

For example below, I'd like to call import on the `User` model and then send a notifications email. Here's my `scheduler.rake` excerpt:

```
require 'elasticsearch/rails/tasks/import'

task :sync_elasticsearch => :environment do
  Rake::Task["elasticsearch:import:model CLASS='User' SCOPE='active' FORCE=y"].invoke
  #additional code to notify via email that this process is complete
end
```

However, I'm getting error: `Don't know how to build task 'elasticsearch:import:model CLASS='User' SCOPE='active' FORCE=y'`. Any suggestions?

**Comment by mogox** [comment]
A bit late but maybe is still helpful, at my company we're using something like this

```ruby
namespace :task do
      desc "description"
      task :sync_elasticsearch => :environment do
        sh "rake environment elasticsearch:import:model CLASS='User' SCOPE='active' FORCE=y"
     end
end
```

**Comment by karmi** [comment]
This syntax is incorrect, `Rake::Task["elasticsearch:import:model CLASS='User' SCOPE='active' FORCE=y"]`

You need to call `Rake::Task["elasticsearch:import:model"].invoke` and provide the environment variables on the comand line, or as @mogox suggest, just wrap it all in a `sh` call.

Sorry for not getting to you sooner!
