### ISSUE TITLE
Records are not returned when the number of matches is over 100.000

### ISSUE THREAD

**Issue by JustusLauten** [elasticsearch/elasticsearch-rails#268]
When the number of results exceeds 100.000, no records are returned when using the "records" method of the elasticsearch gem. 
Is there some kind of setting in the gem or in the elasticsearch server that I need to configure? I couldn't find anything on the web.

Here is my query: 
{:query=>
  {:filtered=>
    {:filter=>
      {:and=>
        [{"geo_distance"=>
           {"distance"=>"50km", "locations"=>[6.959605, 50.9375]}}]}}},
 :post_filter=>{:bool=>{:must=>[]}},
 :aggregations=>
  {:brands=>
    {:filter=>{:exists=>{:field=>"brand"}},
     :aggs=>{:count=>{:terms=>{:field=>"brand", :size=>100}}}},
   :shops=>
    {:filter=>{:exists=>{:field=>"shop_names"}},
     :aggs=>{:count=>{:terms=>{:field=>"shop_names", :size=>100}}}},
   :categories=>
    {:filter=>{:exists=>{:field=>"categories"}},
     :aggs=>
      {:count=>{:terms=>{:field=>"categories.categoryId", :size=>999}}}}},
 :sort=>[]}

Please note that the counts in the aggregations are returned correctly, as well as es_query.results.total.

**Comment by karmi** [comment]
> When the number of results exceeds 100.000, no records are returned when using the "records" method of the elasticsearch gem. 

Sorry for silence on my part! This doesn't make much sense -- the results are always paginated, i.e. only the first xyz results are returned, by default 10. Can you turn on debug logging to see what exactly is send to and from Elasticsearch?

**Comment by JustusLauten** [comment]
No Problem, it turned out that the Problem had to do with inconsistencies between the elasticsearch data and records in the database which were already deleted. The first  paginated results were not present in the database anymore, so it appeared as if no results were found at all.

**Comment by karmi** [comment]
Argh, right, that might be a problem. Also, make sure to use `refresh_index!` eg. in integration tests to make sure the index is uptodate.
