### ISSUE TITLE
Provide a way to switch index at runtime

### ISSUE THREAD

**Issue by bencrouse** [elasticsearch/elasticsearch-rails#271]
I have a need for this in my app, and it would also be helpful for parallelizing tests. Reading through the code/docs I couldn't find a way to do this.

I would be willing to take a shot at implementing this as a lambda that would be called at runtime.

**Comment by karmi** [comment]
@bencrouse Sorry for missing this. When you say "switch index at runtime", what do you mean exactly? 

I think you can just override the `index_name` and implement your own custom logic? Also, there's a setter `MyModel.index_name=`, which you can call anytime -- is it what you're after?

As @lorgio suggest, we support dynamic index names in Model, it _should_ be the same in Persistance of course...

**Comment by bencrouse** [comment]
I worked around this by setting it in the initializer with `index "foo_index_#{Site.current_index}"`, which isn't too big a deal. However, I did and would expect the behavior between Model and Persistence to be consistent.

**Comment by karmi** [comment]
@bencrouse Absolutely, the missing support in peristence is just a failure to implement it in time on my side. Closing this then?

**Comment by bencrouse** [comment]
fine by me
