### ISSUE TITLE
Support for reindexing data without downtime

### ISSUE THREAD

**Issue by mumoshu** [elasticsearch/elasticsearch-rails#291]
Hi, thanks for sharing this great library :)

Do you mind adding support for reindexing data without downtime as described in [the Elasticsearch's documentation](http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/)?

I have achieved it by [re-indexing whole documents parallelly](https://github.com/crowdworks/elasticsearch-model-extensions/blob/master/lib/elasticsearch/model/extensions/batch_updating.rb#L47) in a spare index and [switching the index pointed from an alias](https://github.com/crowdworks/elasticsearch-model-extensions/blob/master/lib/elasticsearch/model/extensions/index_operations.rb#L64) for now.
But the default, or better solutions included in the elasticsearch-model gem are welcome.

**Comment by karmi** [comment]
@mumoshu Closing this in favour of a future pull request, if that's OK?

**Comment by bcackerman** [comment]
+1

**Comment by rafaltrojanowski** [comment]
+1
