### ISSUE TITLE
Rails instrumentation does not work with Elasticsearch::Persistence::Repository

### ISSUE THREAD

**Issue by adamniedzielski** [elasticsearch/elasticsearch-rails#305]
This issue is related to https://github.com/elasticsearch/elasticsearch-rails/issues/238

I'm using Elasticsearch::Persistence::Repository and no Elasticsearch queries are logged and the timer always says: "Elasticsearch: 0.0ms"

Looking at the implementation (https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/instrumentation/railtie.rb) this is not supposed to work.

Can you estimate the complexity of implementation? If it's not hard I can give it a try with PR.

**Comment by adamniedzielski** [comment]
Thanks for your response! I've followed your suggestion and implemented it inside my repository:

```ruby
class ArticleRepository
  [...]

  private
  
    def search_with_logging(query, options = {})
      ActiveSupport::Notifications.instrument "search.elasticsearch",
                                              name: 'Search',
                                              klass: self.class,
                                              search: query do
        search(query, options)
      end
    end
end
```

and I'm calling ```search_with_logging``` instead of ```search```. I'm still using a part of elasticsearch-rails - log subscriber.

**Comment by karmi** [comment]
@adamniedzielski Great! I think it makes sense -- I consider the `Repository` object to be really lightweight, so your solution is exactly what I would do. Closing this, if it's OK?

**Comment by adamniedzielski** [comment]
Fine for me
