### ISSUE TITLE
Pagination can't work well with kaminari

### ISSUE THREAD

**Issue by lazybios** [elasticsearch/elasticsearch-rails#309]
When I use kaminari to pagination Elasticsearch  highlight results, the `page` always can not be found correctly.It will report NoMethodError
 `undefined method page for #<Elasticsearch::Model::Response::Response:0x007f3cc82e9198>`
I can confirm the Elasticsearch's configuration is right. Because I can get search result when I commented the pagination. The page chain clause called like below:
`Issues.search(...).page(params[:page]).per(8).records`

**Comment by karmi** [comment]
@lazybios Any news here?

**Comment by lazybios** [comment]
The problem was caused by put the pagination gem after the elasticsearch gems. I have noticed your new commit the note about the importance of pagination gems order,but the description can be more accurate. I have pull request for fixed it. :)

**Comment by karmi** [comment]
Great! Closing this in favour of #314
