### ISSUE TITLE
Calling Elastic search method in the Model from a Rake Task

### ISSUE THREAD

**Issue by memughal** [elasticsearch/elasticsearch-rails#310]
I want to write a rake task to search in the elastic search and return me records. The search method is written in Model and is working fine. But when I try to run the same method from Rake task it gives me this error:

 Faraday::ConnectionFailed: Connection refused - connect(2) for "fe80::1%lo0" port 9200

My Rake task simply calls the method:

```ruby
namespace :linking do
  desc "Link Soux sources with search"
  task :soux => :environment do

    params = Hash.new
    params[:name] = 'Pullman'
    params[:street] = 'Lindemannstr.'
    params[:zip] = '44137'
    params[:city] = 'DORTMUND'
    params[:country] = 'Deutschland'

    @source = Source.filtered_search params
    @source.each do |item|
      puts "#{item.id}"
    end
  end
end
```

According to my understanding, when I am using "environment" that means that all settings will be used that of the environment. Then why is there problem connecting to the elasticsearch connected to that model.

Thanks in Advance!

**Comment by karmi** [comment]
When you try it in `rails console`, does it work or not?

**Comment by memughal** [comment]
It works in the rails console and returns the resulting records.

**Comment by karmi** [comment]
This seems to indicate that you're using different URL for connection to Elasticsearch, maybe you set it in a Rails initializer? The client will automatically pick up any set/exported `ELASTICSEARCH_URL` environment variable.

**Comment by memughal** [comment]
I am using the default configuration of elasticsearch and I didn't set the Url of the elasticsearch explicitly anywhere, not even in the model. 

I use this in the model to specify the name of the index, just to differentiate between testing and development indices:
index_name("#{Rails.env}-source")

My elasticsearch url is this:
http://localhost:9200/<name-of-the-index>

**Comment by karmi** [comment]
Hmm, for whatever reason the client is connecting to the IPV6 variant of the address -- it's a good thing to set the URL anyway, best way is to just use the `ELASTICSEARCH_URL` environment variable, so:

```bash
ELASTICSEARCH_URL=localhost:9200 bundle exec rails server
ELASTICSEARCH_URL=localhost:9200 bundle exec rails console
ELASTICSEARCH_URL=localhost:9200 bundle exec rake linking:soux
```

etc.

**Comment by memughal** [comment]
Thank you so much for your help it worked. I tried doing the initial configuration it didn't work with localhost:9200 but 127.0.0.1:9200.

```ruby
require 'elasticsearch/model'

Elasticsearch::Model.client = Elasticsearch::Client.new url: '127.0.0.1:9200', log: true
```

Now it works. Thanks!
