### ISSUE TITLE
Elasticsearch model without database

### ISSUE THREAD

**Issue by alolis** [elasticsearch/elasticsearch-rails#315]
Hello,

I was wondering if it's possible to use the elasticsearch-model without a database. In other words, Elasticsearch is my primary store and I do want to have the easiness of the elasticsearch-model, without the need to have an ActiveRecord table.

Thanks for your time

**Comment by alolis** [comment]
It seems that I will answer to myself: http://www.elasticsearch.org/guide/en/elasticsearch/client/ruby-api/current/_persistence.html

I do not know how I missed that

**Comment by karmi** [comment]
@alolis Cool! :)

**Comment by liqites** [comment]
@alolis Thanks man

**Comment by Startouf** [comment]
For future readers [this link will bring you directly to the doc](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-persistence#usage)
