### ISSUE TITLE
Model attribute type binary

### ISSUE THREAD

**Issue by alolis** [elasticsearch/elasticsearch-rails#317]
Hello,

I have a property in my elasticsearch schema that is binary type (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-core-types.html).

I am trying to declare this attribute in my elasticsearch model but, I can not seem to be able to find in the documentation a 'Binary' type or something similar.

Am I supposed to use the following instead?

`attribute :my_property, String,  mapping: { type: 'binary'}`

Thank you for your time

**Comment by karmi** [comment]
Yeah, using the [`binary`](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-core-types.html#binary) type is correct, the `mapping` method simply wraps the regular Elasticsearch syntax. Just be aware that it won't (de)serialiaze the content into/from Base64, you have to do it yourself. I assume this is related to `elasticsearch-persistence` -- the README has information about handling this exact situation.

**Comment by alolis** [comment]
Thanks karmi. Yeah I assumed it wont encode/decode the data. I will have a look at the README.

**Comment by alolis** [comment]
Sorry for re-opening this, but i am looking at my elasticsearch server and the properties of my data and their type does not match the one i specified in my model. For example for my binary attribute (which i mention in my first post), I see that it's set as string instead of binary and for a couple of others, which i specified short in the mapping, i see that they are long. 

When exactly is the mapping being created? Should I initialize it first before I start saving data?

**Comment by karmi** [comment]
@alolis Yeah, please see `create_index! force: true`

**Comment by alolis** [comment]
@karmi , thanks for getting back. Is there a recommended way for initializing the indexes via rails initializers (or any other alternative)? It should only be called once and only if the indexes do not exist

**Comment by karmi** [comment]
Have you seen the templates for the example applications in `elasticsearch-rails/elasticsearch-rails`?

**Comment by alolis** [comment]
@karmi , I just checked all of them but I am not sure what exactly am I supposed to find in there. I couldn't locate an initializer or something that can answer my question. Perhaps I missed it?

**Comment by alolis** [comment]
Well, it seems that everything is working normally. I had a syntax error in my model mappings and the mapper parsing was throwing an exception and a automatic mapping was being used instead.

I had this in my model mappings:

`attribute :file_list, Array, mapping: {type: 'nested', properties: {name: 'string', size: 'long'}}`

but the correct one of course is 

`attribute :file_list, Array, mapping: {type: 'nested', properties: {name: {type: 'string'}, size: {type: 'long'}}}`

**Comment by alolis** [comment]
This example was helpful: https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/index_manager.rb

I ended up doing something like that and calling `rails runner 'IndexManager.create_index force: true' from "."` from the command line.
