### ISSUE TITLE
Models with same index but different document type

### ISSUE THREAD

**Issue by alolis** [elasticsearch/elasticsearch-rails#322]
Hello,

I have a few models that all belong to the same index but they have different document type. My plan was to create a base model, which includes all the ES attributes and inherit from that and make something like this:

````
class Base
  index_name 'my_index'

  attribute :title,  String, mapping: {fields: {raw: {type: 'string', index: 'not_analyzed'}}}
  attribute :name, String
end

class Foo < Base
  document_type 'foo'
end
````
The above unfortunately will not inherit  the ES attributes of the base model. Is there a workaround for this? I do not want to copy paste all attributes of the Base to all my models.

**Comment by alolis** [comment]
I think this might be related with https://github.com/elasticsearch/elasticsearch-rails/issues/279

**Comment by alolis** [comment]
I used a base `module` and it seems that it's working properly now. If there is a better way please let me know.

And while we are on the subject, how do I push the mappings for each model to the same index? `Model.create_index!` will only overwrite the ones I have.

**Comment by karmi** [comment]
@alolis Have a look here, https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/index_manager.rb and the corresponding example Rails application.

**Comment by alolis** [comment]
Thanks @karmi
