### ISSUE TITLE
Override Implicit Pagination

### ISSUE THREAD

**Issue by jeebster** [elasticsearch/elasticsearch-rails#326]
https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/response/pagination.rb#L17

I think it's great that pagination is implicitly included into ```ElasticSearch::Model::Results``` and ```ElasticSearch::Model::Records```, however, there are scenarios where returning full, unpaginated, results and records is desirable. I would like to discuss the possibility of adding an option to toggle pagination and the required work to do so. I'm more than happy to start working on a PR once a decision has been reached.

**Comment by jeebster** [comment]
I believe this is my mistake for not understanding elasticsearch's implicit use of pagination: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-from-size.html

**Comment by karmi** [comment]
@jeebster Thanks for clarifying this -- I was a bit confused as to what you mean and wanted to have a better look, but got sidetracked by other work.

**Comment by jeebster** [comment]
@karmi I have a sizeable dataset that I need to run some calculations against. Unfortunately, due to how my data is modeled, I cannot harness Elasticsearch's aggregation. I was quarreling with fetching multiple pages of data to retrieve the desired documents and realized I could bump up the ```size``` parameter accordingly. I started perusing through the [Scan and Scroll API](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/scan-scroll.html) but I'm not sure if this supported in the ```elasticsearch-rails``` library. Is this something we're able to use?

**Comment by karmi** [comment]
Yes, Scan & Scroll is exactly what you're after (and you can even do aggregations as part of the request)

The `elasticsearch-rails` library is a set of high-level integrations (Rails models, persistence, etc), but all the underlying power comes from the [`elasticsearch-ruby`](https://github.com/elasticsearch/elasticsearch-ruby) library -- please have a look at it.

Have a look at documentation and full example for scan&scroll here: http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#scroll-instance_method
