### ISSUE TITLE
Template lacking an actual search form

### ISSUE THREAD

**Issue by cyllu2** [elasticsearch/elasticsearch-rails#327]
The sample template you provide lacks an actual search form, which is kinda the whole reason you want to check it out in the first place.

Also, template 02 and 03 don't exist at all.

**Comment by karmi** [comment]
Hi, any links? See eg. https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/01-basic.rb#L217 ?

**Comment by cyllu2** [comment]
I'm ultra confused. I created another one and put it here: https://github.com/cyllu2/elasticsearch_app

Is there a form there that I'm somehow managing to miss?

**Comment by karmi** [comment]
@cyllu2 This is not working. Can you please provide all the steps you did, command you executed, and so on?

**Comment by cyllu2** [comment]
"rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb"

That's all I did and that's all it says I have to do.

**Comment by karmi** [comment]
@cyllu2 All right! -- tried it myself, and for some reason the form isn't inserted into index.html.erb from the template (see the link above). I'm looking into it.

**Comment by karmi** [comment]
@cyllu2 There's been an issue with incorrect regex in the 01-pretty.rb template. It has been fixed in the attached commit, please run the command again. Thanks for the report!
