### ISSUE TITLE
NoMethodError for Elasticsearch::Model methods after including via concern

### ISSUE THREAD

**Issue by jraczak** [elasticsearch/elasticsearch-rails#340]
@karmi  - Sandra Boyd recommended I work through issues to share the trouble I'm having. Details below - thanks in advance.

I've included Elasticsearch::Model through a concern, as is recommended. When attempting to perform model operations such as create_index!, both with and without the _elasticsearch_ namespace, I am met with NoMethodErrors. `import` and `search`, however, seem to work with no issues. Here's my setup.

    #app/models/concerns/elasticsearch_user.rb
      require 'active_support/concern'

      module ElasticsearchUser
        extend ActiveSupport::Concern
 
        included do
          require 'elasticsearch/model'
          include Elasticsearch::Model
          include Elasticsearch::Model::Indexing
   
         #mapping do
         #  to-do
         #end
    
         #def self.search(query)
         #  write a different search later
         #end
      end
    end`

    # User.rb
    ...
    # Elasticsearch configuration
    include ElasticsearchUser
    # index_name "users" <-- This value is inferred automatically by the model name
    settings index: { number_of_shards: 1 }

I've also tried including Elasticsearch::Model directly in my model definition to no avail. Thanks much for any guidance...

**Comment by karmi** [comment]
Hi Justin, yes, using Github issues for questions is perfectly fine.

Your setup looks OK -- I just wouldn't put the `require` statement into to `included` hook, that should be left to Bundler, Rails, application main file, etc.

You have to call the `create_index!`method via the `__elasticsearch__` proxy, see https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model#the-__elasticsearch__-proxy. The reason for this is not to litter the recieving class namespace with dozens of loose methods.

See the https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model#updating-the-documents-in-the-index section for information about updating documents.

Finally, there's a complex example of the concern-based integration here: https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/searchable.rb -- I suggest to first generate the example applications, look around the code, and see what you can use in your own codebase.

**Comment by jraczak** [comment]
@karmi As I mentioned, I tried the methods both with and without _elasticsearch_ (as the documentation indicates that it is not necessary if these methods are not already defined on the model). The results are the same. 

I reviewed the sample template before implementing. Unfortunately it doesn't speak to the issue I'm having, which is the Elasticsearch methods not being made available to the class. Everything is defined and included as instructed.

**Comment by karmi** [comment]
@jraczak No, these method are only available via the proxy; see https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model.rb#L65

I don't have any explanation why a concern model wouldn't work, precisely because the "03-expert" template runs fine with it...

I suggest you try to "break" the working [`activerecord_article.rb]`(https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_article.rb#L31-L32) example, by declaring the integration in a concern.

**Comment by jraczak** [comment]
@karmi I added some logging inside the search method in my module to make sure we were getting that far. The module is in fact being included because I see the output in the terminal. However, I get the complaint that `_elasticsearch_` variable or method is not defined. 

    ##elasticsearch_user.rb
    ...
    def self.search(query)
      puts 'we made it to search'
      _elasticsearch_.search(
        {
	        query: {
		        multi_match: {
			        query: query,
			        fields: ['username^2', 'email', 'full_name']
		        }
	        }
        }
      )
    end

Terminal says: 

    1.9.1 :033 > User.search('justin')
    we made it to search
    NameError: undefined local variable or method `_elasticsearch_' for #<Class:0x007f839a1b19b0>

So the problem is specifically with elasticsearch making it in. I've set everything up according to the docs - what could I be missing?

**Comment by karmi** [comment]
The proxy object is called `__elasticsearch__` -- notice the double underscore.

**Comment by jraczak** [comment]
-_- Of all the things... Defeated by my novice level. That seems to have me rolling again. Thanks a lot for the help Karel, looking forward to moving forward with the migration from solr.

**Comment by karmi** [comment]
@jraczak Great! Best is to ask via Github issues if you bump into something.
